### ISSUE TITLE
run status show status of latest finished stage

### ISSUE THREAD

**Issue by hrvolapeter** [jenkins-x/jx-pipelines-visualizer#100]
If build consists from multiple stages and some stages are still running the status show status "Succeded" I suspect that the status bar just show status of latest finished stage. The same seems to be problem with run overview where we can get negative duration with multi-stage (task) builds. Where duration seems to be (time of latest finished task) - (time of latest started task)

**Comment by vbehar** [comment]
what are the statuses in the PipelineActivity? if you check the YAML representation of the pipelineactivity for example.
usually the jx-pipelines-visualizer just display the status of the pipeline, which is defined by https://github.com/jenkins-x-plugins/jx-build-controller

**Comment by hrvolapeter** [comment]
During the execution it looks like:
```yaml
  steps:
  - kind: Stage
    stage:
      completedTimestamp: "2021-02-08T15:44:07Z"
      name: git clone
      startedTimestamp: "2021-02-08T15:44:01Z"
      status: Succeeded
      steps:
      - completedTimestamp: "2021-02-08T15:44:02Z"
        name: Git Clone
        startedTimestamp: "2021-02-08T15:44:01Z"
        status: Succeeded
      - completedTimestamp: "2021-02-08T15:44:04Z"
        name: Next Version
        startedTimestamp: "2021-02-08T15:44:03Z"
        status: Succeeded
      - completedTimestamp: "2021-02-08T15:44:07Z"
        name: Jx Variables
        startedTimestamp: "2021-02-08T15:44:04Z"
        status: Succeeded
  - kind: Stage
    stage:
      name: helmfile apply
      startedTimestamp: "2021-02-08T15:44:09Z"
      status: Pending
      steps:
      - name: Helmfile Apply
        startedTimestamp: "2021-02-08T15:44:09Z"
        status: Pending
status: {}
```
While status in the UI show Succeded
