### ISSUE TITLE
Log  long-term does not support S3 compatible API url

### ISSUE THREAD

**Issue by wowq** [jenkins-x/jx-pipelines-visualizer#114]
I have configured the content related to log storage in `jx-requirements.yml`
```  
storage:
  - name: repository
    url: xxxxx
  - name: logs
    url: s3://jx3-logs?region=oss&endpoint=https://oss-xxxx.aliyuncs.com
```
Logs can be written correctly, but in activity, URLs are simply spliced together.The log cannot be viewed normally in JX pipelines visualizer

```
spec:
  baseSHA: 67069742852ef2c56bcc495ab1d3bce72ad09526
  batchPipelineActivity: {}
  build: "4"
  buildLogsUrl: s3://jx3-logs?region=oss&endpoint=https://oss-xxx.aliyuncs.com/jenkins-x/logs/ops/gocidemo/PR-1/4.log
```
